In [2]:
# script para generar los archivos de montos, sucursales y ventas a partir del archivo de ventas original
# como usar => primero descargar el file de tibco, cambiar el nombre a "Ventas_Rango_de_fechas.xls" 
# moverlo a la carpeta ventas_mod, luego abrir el archivo en excel y eliminar la primera fila y cambiar la columna monto a enteros, 
# sin decimales, luego ejecutar este script. Se generarán los archivos montos.csv, sucursales.csv y ventas.csv en la carpeta ventas_mod


import pandas as pd
import xlrd

df = pd.read_excel('ventas_mod/Ventas_Rango_de_fechas.xls')
pd.set_option('display.width', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)

for col in ['FAMILIA', 'PRODUCTO', 'VARIACION']:
    df[col] = df[col].astype(str).str.strip().str.replace(r'\s+', ' ', regex=True)

montos = df.copy()
sucursales = df.copy()
ventas = df.copy()

# tabla de montos
montos = montos.drop(columns=['SUCURSAL', 'CANTIDAD']).groupby(['FAMILIA', 'PRODUCTO', 'VARIACION'], dropna=False)['MONTO'].sum().reset_index()
#display(montos)


#tabla de sucursales
columnas_table_sucursales = [col for col in df.columns if col not in ['SUCURSAL', 'MONTO']]
sucursales = sucursales.drop(columns=columnas_table_sucursales).groupby('SUCURSAL', dropna=False).sum().reset_index()
#display(sucursales)



## tabla de ventas por sucursal
columnas_index = [col for col in ventas.columns if col not in ['SUCURSAL', 'CANTIDAD']]
for col in columnas_index:
    ventas[col] = ventas[col].fillna('SIN DATO')

ventas = ventas.pivot_table(index=columnas_index, columns='SUCURSAL', values='CANTIDAD', aggfunc='sum', fill_value=0).reset_index()
ventas = ventas.drop(columns=['MONTO'])

for col in ['FAMILIA', 'PRODUCTO', 'VARIACION']:
    ventas[col] = ventas[col].astype(str).str.strip().str.replace(r'\s+', ' ', regex=True)

columnas_ventas = [col for col in ventas.columns if col not in ['FAMILIA', 'PRODUCTO', 'VARIACION']]
columnas_identificadoras = ['FAMILIA', 'PRODUCTO', 'VARIACION']
ventas = ventas.groupby(columnas_identificadoras, dropna=False)[columnas_ventas].sum().reset_index()

ventas.columns.name = None   # <- elimina el "SUCURSAL" fantasma en el índice
ventas[['FAMILIA', 'PRODUCTO', 'VARIACION']] = ventas[['FAMILIA', 'PRODUCTO', 'VARIACION']].replace('SIN DATO', pd.NA)


ventas = ventas.rename(columns={'C.C. TITAN': 'TITAN', 'CC PARQUE COLINA': 'COLINA'})

ventas = ventas.merge(montos, on=['FAMILIA', 'PRODUCTO', 'VARIACION'], how='left')
ventas = ventas.rename(columns={'MONTO': 'VALOR'})
ventas['VALOR'] = ventas['VALOR'].astype('Int64')
display(ventas)
montos.to_csv('ventas_mod/montos.csv', sep='|', index=False)
sucursales.to_csv('ventas_mod/sucursales.csv', sep='|', index=False)
ventas.to_csv('ventas_mod/ventas.csv', sep='|', index=False)

,FAMILIA,PRODUCTO,VARIACION,ANDINO,TITAN,CALLE 109,CALLE 122,CALLE 79,COLINA,CEDRITOS,CHIA,FABRICA,FONTANAR,SALITRE,SANTAFE,VALOR
0,ARITOS,ARITO,NaN,13,9,11,33,12,25,29,16,33,19,16,16,5685300
1,ARITOS,ARITO AREQUIPE,NaN,6,5,0,2,2,3,3,2,0,2,2,3,721800
2,ARITOS,ARITO CHOCOFLAN,NaN,2,2,1,1,1,0,2,2,0,0,2,0,310700
3,ARITOS,ARITO CHOCOLATE,NaN,4,4,2,1,3,4,4,5,0,2,2,1,764800
4,ARITOS,ARITO LIMON,NaN,13,8,3,9,7,10,10,6,5,2,6,9,2136840
5,ARITOS,ARITO MARACUYA,NaN,7,8,3,7,2,8,10,6,2,5,7,7,1728120
6,ARITOS,ARITO PISTACHO,NaN,0,0,0,0,0,1,0,0,0,0,0,0,23900
7,BEBIDAS CALIENTES,AMERICANO,NaN,48,33,13,36,13,61,20,35,0,33,36,24,2851200
8,BEBIDAS CALIENTES,AMERICANO DOBLE,NaN,0,1,0,1,0,1,0,0,0,0,0,0,26100
9,BEBIDAS CALIENTES,AROMATICA HIERBABUENA,NaN,3,6,0,5,1,1,0,1,0,5,6,2,207000
10,BEBIDAS CALIENTES,Aromatica de Frutas,NaN,3,3,3,4,1,2,0,6,0,5,2,1,273000
11,BEBIDAS CALIENTES,BLUE CHAI,NaN,1,0,0,0,0,0,2,0,0,3,0,0,69000
12,BEBIDAS CALIENTES,CAFÉ LATTE,NaN,15,2,1,8,0,8,3,3,0,10,9,4,711900
13,BEBIDAS CALIENTES,CAPUCHINO,NaN,19,33,11,17,6,24,12,19,0,23,2,12,1958000
14,BEBIDAS CALIENTES,CHAI AMATISTA,NaN,0,2,0,0,0,0,2,2,0,5,0,1,138000
15,BEBIDAS CALIENTES,EXPRESSO,NaN,2,0,0,0,0,1,1,2,0,0,2,0,64800
16,BEBIDAS CALIENTES,MACCHIATO,NaN,2,0,1,1,0,0,0,1,0,1,2,1,85500
17,BEBIDAS CALIENTES,MILO,NaN,1,2,0,0,0,0,0,0,0,3,1,0,79100
18,BEBIDAS CALIENTES,TE,EN AGUA,4,2,0,1,0,1,2,1,0,0,0,1,126000
19,BEBIDAS CALIENTES,TE,EN LECHE,0,0,1,0,0,0,0,0,0,0,0,0,11900
20,BEBIDAS CALIENTES,TE CHAI,Te Chai,4,2,0,0,2,2,2,2,0,5,0,0,218500
21,BEBIDAS CALIENTES,TE MATCHA,NaN,0,1,0,0,0,0,1,0,0,0,3,0,57500
22,BEBIDAS CALIENTES,TE MATCHA CHAI,NaN,0,0,1,0,0,0,0,0,0,1,0,0,23000
23,BOMBAS,BOMBA GRANDE,NaN,0,0,0,1,0,0,1,0,0,0,0,0,68000
24,BOMBAS,BOMBA MEDIANA,NaN,1,0,0,0,0,1,0,0,0,0,0,0,38200
25,BROWNIES,BROWNIE,NaN,0,1,0,0,0,1,0,0,0,0,0,0,23200
26,BROWNIES,CAJA MINIBROWNIES X 16,NaN,1,0,0,1,1,3,0,0,0,1,0,1,435900
27,BROWNIES,CAJAMINI BROWNIES,NaN,2,1,0,1,1,1,3,0,1,0,2,0,345600
28,BROWNIES,CHIPS NEGRO,NaN,1,1,0,0,0,0,0,0,0,2,0,0,46400
29,BROWNIES,CHOCOLATE,NaN,6,3,3,3,1,3,3,3,0,5,2,3,407200
30,BROWNIES,MINI BROWNIES,NaN,0,0,24,0,1,0,0,2,0,0,0,1,98500
31,BROWNIES,M´M´S,NaN,1,0,0,0,0,1,1,1,0,0,1,0,59200
32,BROWNIES,OREO,NaN,0,1,0,0,0,0,1,0,0,2,0,0,46400
33,CHEESECAKE,CHEESECAKE SIN AZUCAR,1 NUMERO 6 PX,0,0,0,0,0,0,0,0,2,0,0,0,214200
34,CHEESECAKE,CHEESECAKE SIN AZUCAR,ARITO LIGHT,27,19,12,31,12,24,25,24,8,7,22,18,5687350
35,CHEESECAKE,CHEESECAKE SIN AZUCAR,DOBLE,0,1,1,0,1,1,2,1,1,1,2,1,2014800
36,CHEESECAKE,CHEESECAKE SIN AZUCAR,MEDIANO,0,4,4,11,2,4,10,3,4,3,4,3,6115000
37,CHEESECAKE,CHEESECAKE SIN AZUCAR,MEDIANO CORAZON,0,0,2,1,1,0,1,0,2,1,0,1,1079100
38,CHEESECAKE,CHEESECAKE SIN AZUCAR,MINIMEDIANO,1,3,4,5,1,3,4,3,4,2,2,1,2638800
39,CHEESECAKE,CHEESECAKE SIN AZUCAR,MINIMEDIANO CORAZON,4,0,2,2,0,2,3,1,0,1,2,1,1502100
40,CHEESECAKE,CHEESECAKE SIN AZUCAR,PX,14,8,0,5,5,12,12,8,0,25,5,0,1900400
41,CHEESECAKE,CHEESECAKE SIN AZUCAR,TRIPLE,0,1,0,2,0,0,1,1,1,0,0,0,1199800
42,CHEESECAKE,CHEESECAKE TRADICIONAL,DOBLE,0,0,2,4,2,1,2,1,2,1,3,1,3098200
43,CHEESECAKE,CHEESECAKE TRADICIONAL,MEDIANO,1,4,2,8,2,3,10,0,2,4,0,0,4205600
44,CHEESECAKE,CHEESECAKE TRADICIONAL,MEDIANO CORAZON,1,1,2,4,0,2,0,1,3,0,1,1,1918600
45,CHEESECAKE,CHEESECAKE TRADICIONAL,MINIMEDIANO,1,3,1,4,6,1,3,1,3,2,1,1,2070000
46,CHEESECAKE,CHEESECAKE TRADICIONAL,MINIMEDIANO CORAZON,1,0,2,3,0,1,1,0,2,1,3,1,1196000
47,CHEESECAKE,CHEESECAKE TRADICIONAL,PX,21,22,4,16,6,18,6,2,0,8,17,3,2471700
48,CHEESECAKE,CHEESECAKE TRADICIONAL,TRIPLE,1,2,0,2,0,1,2,1,2,1,0,0,2395800
49,CHEESECAKE,bite size,NaN,0,0,0,2,17,28,0,33,0,23,7,8,831600
50,CHEESECAKE,mini bites por 12 unidades,NaN,4,4,4,3,3,3,5,2,9,3,3,1,3771600
51,CHEESECAKE,mini bites por 16 unidades,NaN,2,0,0,3,0,1,0,1,0,1,2,1,1232000
52,CHEESECAKE,mini bites por 4 unidades,NaN,0,1,0,0,0,0,0,0,0,0,2,0,84000
53,CHEESECAKE,mini bites por 8 unidades,NaN,0,5,3,7,0,1,5,1,2,0,3,1,1635200
54,CHEESECAKE ESPECIAL,AMERICAN CUPS,CHOCO OREO,2,0,2,2,1,1,1,1,0,0,1,1,264000
55,CHEESECAKE ESPECIAL,AMERICAN CUPS,CHOCORRAMO,1,3,0,0,0,2,0,1,0,0,1,2,220000
56,CHEESECAKE ESPECIAL,AMERICAN CUPS,FRAMBUESA,3,5,1,3,0,3,4,3,1,1,3,2,640200
57,CHEESECAKE ESPECIAL,AMERICAN CUPS,RED LEMON,0,1,2,2,0,1,0,1,0,2,1,0,222200
58,CHEESECAKE ESPECIAL,AMERICAN CUPS,SHORTCAKE,0,1,0,2,0,1,0,1,0,2,0,0,156200
59,CHEESECAKE ESPECIAL,AMERICAN CUPS,TRES LECHES ZERO,2,2,2,3,0,2,0,0,0,1,2,1,332200
60,CHEESECAKE ESPECIAL,AMERICAN CUPS,ZANAHORIA,1,2,1,2,2,2,1,1,0,1,2,2,367400
61,CHEESECAKE ESPECIAL,ARITO ESPECIAL,ARANDANOS,7,8,2,4,1,6,5,3,0,2,3,4,1153620
62,CHEESECAKE ESPECIAL,ARITO ESPECIAL,FRAMBUESA,10,8,4,6,2,5,4,3,0,2,5,4,1372860
63,CHEESECAKE ESPECIAL,ARITO ESPECIAL,VASCO,3,5,1,1,2,2,2,1,0,0,1,0,451400
64,CHEESECAKE ESPECIAL,ARITO ESPECIAL,VASCO ARANDANO,3,2,3,2,2,1,2,3,0,1,2,3,617200
65,CHEESECAKE ESPECIAL,ARITO ESPECIAL,VASCO LIMON,1,0,0,0,0,0,0,0,0,0,0,0,25500
66,CHEESECAKE ESPECIAL,ARITO ESPECIAL,VASCO ZERO,4,1,3,2,3,2,2,3,0,1,1,2,604200
67,CHEESECAKE ESPECIAL,DOBLE 15 PX,FRUTOS ROJOS,0,0,0,0,0,0,0,0,2,0,0,0,376000
68,CHEESECAKE ESPECIAL,MEDIANO 10 PX,BLACKBERRY/BROWNIE,0,0,1,0,0,1,1,0,0,0,0,0,413900
69,CHEESECAKE ESPECIAL,MEDIANO 10 PX,BROWNIE,0,0,0,0,0,0,1,0,0,0,0,0,133500
70,CHEESECAKE ESPECIAL,MEDIANO 10 PX,FRAMBUESA,1,2,2,1,1,1,1,1,1,0,1,0,1720900
71,CHEESECAKE ESPECIAL,MEDIANO 10 PX,FRUTOS ROJOS,1,3,2,4,1,3,3,3,1,1,2,2,3538000
72,CHEESECAKE ESPECIAL,MEDIANO 10 PX,FRUTOS ROJOS ZERO,2,2,1,2,1,2,3,2,0,2,2,0,2630900
73,CHEESECAKE ESPECIAL,MEDIANO 10 PX,LIMON,0,1,1,0,0,1,0,0,0,0,0,0,413900
74,CHEESECAKE ESPECIAL,MEDIANO 10 PX,MARACUYA,1,1,0,1,1,1,0,1,1,0,1,1,1201500
75,CHEESECAKE ESPECIAL,MEDIANO 10 PX,SOLO FRESAS CON MENSAJE,0,0,0,0,0,0,0,0,1,0,0,0,133500
76,CHEESECAKE ESPECIAL,MONOPORCION ZERO,FRUTOS ROJOS,10,7,5,12,1,7,5,6,0,8,2,6,1576700
77,CHEESECAKE ESPECIAL,PORCION,NaN,5,4,0,0,0,0,0,0,0,0,0,0,197100
78,CHOCOLATERIA,COLOMBINAS,NaN,1,2,0,0,1,3,0,0,0,0,0,0,124300
79,CHOCOLATERIA,VELAS PEQUEÑAS,NaN,3,4,3,6,3,1,2,4,1,1,4,2,605800
80,GALLETERIA,ALFAJORES,NaN,2,2,0,0,1,3,2,8,0,3,2,0,204700
81,GALLETERIA,CAJA GALLETAS OJITOS MERMELADA,NaN,0,0,1,1,1,0,1,0,0,1,1,1,275200
82,GALLETERIA,CAJA GALLETAS SURTIDAS,NaN,0,0,1,1,1,0,0,1,0,0,0,1,191000
83,GALLETERIA,CORAZONES ACHOCOLATADOS,NaN,7,3,0,8,2,6,1,9,0,7,2,0,315000
84,GALLETERIA,GALLETAS AVENA,NaN,0,1,0,0,1,2,1,0,0,1,0,0,61800
85,GALLETERIA,GALLETAS CHOCOLACHIPS,NaN,2,2,0,1,0,1,2,0,0,2,0,0,103000
86,GALLETERIA,GALLETAS OJITOS MERMELADA,NaN,3,2,5,9,8,2,3,4,0,11,3,4,237600
87,GALLETERIA,GALLETERIA,ALMENDRA,0,0,0,0,0,7,0,2,0,3,3,2,61200
88,GALLETERIA,Mini Alfajores,NaN,15,4,7,4,4,11,2,8,0,7,4,4,252000
89,GALLETERIA,PAQUETICO GALLETA JALEA,NaN,0,0,0,3,0,1,6,4,0,0,0,0,64400
90,GRUPO BEBIDAS FRIAS,AGUA CON GAS,NaN,12,3,1,11,0,10,0,3,0,10,0,5,418000
91,GRUPO BEBIDAS FRIAS,AGUA NORMAL,NaN,48,8,3,5,3,31,6,22,0,23,4,5,1200800
92,GRUPO BEBIDAS FRIAS,BRETAÑA,NaN,4,0,0,0,0,0,2,0,0,0,0,0,52200
93,GRUPO BEBIDAS FRIAS,GASEOSA,COCACOLA DIETY,7,5,2,5,1,4,2,2,0,8,2,1,342000
94,GRUPO BEBIDAS FRIAS,GASEOSA,COCACOLA NORMAL,9,0,1,3,0,0,3,3,0,1,2,0,192300
95,GRUPO BEBIDAS FRIAS,HATSU,NaN,5,3,2,0,1,4,1,3,0,0,0,0,178600
96,GRUPO BEBIDAS FRIAS,JUGO,AGUA,0,4,0,0,0,0,0,0,0,0,1,0,53500
97,GRUPO BEBIDAS FRIAS,JUGO,LECHE,1,1,0,0,0,0,0,0,0,0,0,0,22400
98,GRUPO BEBIDAS FRIAS,LIMONADA,FRAMBUESA,1,0,1,0,1,2,0,1,0,3,0,0,103500
99,GRUPO BEBIDAS FRIAS,LIMONADA,SANDIA Y ALBAHACA,1,2,1,0,0,1,2,1,0,0,0,1,103500
100,GRUPO BEBIDAS FRIAS,MILO FRIO,NaN,0,0,0,1,0,0,0,0,0,0,0,0,11300
101,GRUPO BEBIDAS FRIAS,MR. TE,NaN,0,1,0,0,0,6,0,0,0,2,2,2,75400
102,GRUPO BEBIDAS FRIAS,SODA DE FRUTA,FRUTOS ROJOS,0,0,0,0,0,0,0,0,0,1,0,0,13000
103,GRUPO BEBIDAS FRIAS,SODA DE FRUTA,LULO,1,0,0,1,0,0,0,0,0,1,0,0,39000
104,GRUPO BEBIDAS FRIAS,SODA DE FRUTA,MARACUYA,1,0,0,0,0,0,0,0,0,1,0,0,26000
105,GRUPO BEBIDAS FRIAS,VASO LECHE,NaN,0,1,1,0,0,0,0,0,0,0,1,0,20700
106,HOJALDRES DE SAL,PALOS DE QUESO,NaN,6,5,2,1,0,6,1,4,0,10,4,1,436000
107,HOJALDRES DE SAL,PASTELES DE POLLO,NaN,3,6,5,5,0,7,2,11,0,20,2,2,774900
108,MILHOJAS,PXVAINILLA AREQUIPE,NaN,15,5,0,5,4,10,0,4,1,0,3,4,816000
109,PIE,LIMON MINI,NaN,7,5,6,5,5,8,4,2,2,5,3,4,1310600
110,PIE,PIE MANZANA,NaN,4,4,0,3,3,0,2,0,0,1,1,2,458600
111,PONQUES,MINIPONQUE,Frutos Rojos,1,2,0,1,2,1,1,1,0,0,1,0,299600
112,PONQUES,MINIPONQUE,KINDER,1,1,1,0,1,0,0,1,0,1,1,0,232500
113,PONQUES,MINIPONQUE,M´M´S,0,0,0,0,0,0,0,0,1,0,0,0,31000
114,PONQUES,MINIPONQUE,NUTELLA,0,0,0,0,0,0,0,0,0,0,1,0,31000
115,PONQUES,MINIPONQUE,OREO,2,2,2,1,1,3,0,1,0,1,1,3,536300
116,PONQUES,MINIPONQUE,REDVELVET,1,3,0,3,2,4,2,1,6,2,3,2,887400
117,PONQUES,MINIPONQUE,REDVELVET ESPECIAL,2,1,1,3,2,3,3,3,0,2,2,2,722500
118,PONQUES,MINIPONQUE,T. CHOCOLATE SIN AZUCAR AÑADIDO,0,1,0,1,0,0,1,0,0,0,1,0,127100
119,PONQUES,PX,NaN,5,0,0,0,0,0,0,0,0,0,0,0,80500
120,PONQUES,TORTA 12 PX,KINDER,0,0,0,0,0,0,0,0,1,0,0,0,137500
121,PONQUES,TORTA 12 PX,NUTELLA,0,0,0,0,0,0,0,0,1,0,0,0,137500
122,PONQUES,TORTA 12 PX,OREO,0,0,0,0,0,0,0,0,1,0,0,0,148500
123,PONQUES,TORTA 12 PX,SELVA NEGRA,0,0,0,0,0,0,0,0,2,0,0,0,297000
124,PONQUES,TORTA 8 PX,CHOCOFRAMBUESA,0,1,0,0,1,0,0,0,0,0,0,0,204800
125,PONQUES,TORTA 8 PX,GANACHE,1,1,0,0,0,0,1,1,0,0,0,0,367800
126,PONQUES,TORTA 8 PX,KINDER,0,1,1,1,1,1,0,1,0,0,0,0,589300
127,PONQUES,TORTA 8 PX,RED VELVET,0,1,1,0,1,1,0,0,1,1,1,1,726600
128,PONQUES,TORTA 8 PX,SELVA NEGRA,0,1,0,0,0,0,0,0,0,0,0,0,102400
129,PONQUES,TORTA 8 PX,SHORTCAKE,0,1,0,0,0,0,0,0,0,0,0,0,89700
130,PONQUES,TORTA 8 PX,T. CHOCOL,0,0,1,0,0,0,0,0,0,0,0,0,102400
131,PONQUES,TORTA 8 PX,ZANAHORIA,1,1,1,2,0,0,1,0,0,1,0,0,627900
132,PROMOCIONES,CHEESECAKE & CAFFEE,NaN,0,0,0,0,0,0,0,3,0,0,0,0,71700
133,PROMOCIONES,PROMOCION 3X4 Cheese cake tradicional,NaN,1,1,1,0,0,0,1,1,0,0,0,0,366850
134,PROMOCIONES,PROMOCION 3X4 Cheese light,NaN,0,1,0,2,2,0,1,0,1,0,0,0,488400
135,TARTALETA,TARTALETA NORMAL,GRANDE 12 PX,0,0,0,0,0,0,0,0,0,0,1,0,175600
136,TARTALETA,TARTALETA NORMAL,GRANDE 20 PX,0,0,0,0,0,0,0,0,1,0,0,0,211200
137,TARTALETA,TARTALETA NORMAL,MEDIANA 8 PX,0,0,0,3,0,0,3,1,0,0,0,0,1001200
138,TARTALETA,TARTALETA NORMAL,MINITARTALETA,14,14,7,10,5,14,16,3,4,9,10,2,2828080
139,TARTALETA,TARTALETA NORMAL,PX,0,0,0,0,0,0,1,0,0,0,0,0,20100
140,TARTALETA,TARTALETA SIN AZUCAR,MEDIANA 8 PX,1,0,0,0,0,0,1,0,1,0,0,0,433200
141,TARTALETA,TARTALETA SIN AZUCAR,MINITARTALETA,11,8,5,11,2,12,14,12,2,9,9,5,2638310
142,TARTALETA,TARTALETA SIN AZUCAR,PX,0,0,0,2,0,0,0,0,0,0,0,0,42400
143,TOPPERS,TOPPERS GRANDE,NaN,0,0,0,0,0,0,1,0,1,0,0,0,28000
144,TORTA 3 LECHES,COPITAS T. 3 Leches,NaN,1,3,1,0,2,2,0,2,0,0,2,1,316300
145,TORTA 3 LECHES,T. 3 Leches TORTA 8 PX,NaN,0,0,0,1,0,1,0,0,0,0,0,0,179400
146,VARIOS,DOMICILIO,NaN,0,0,0,0,0,0,0,0,38,0,0,0,475000

In [4]:
# script para generar el archivo resultado.csv a partir de los archivos ventas.csv y test_stock.txt
# este debe ser nombre de las columnas del archivo stock.txt debe ser el mismo que el de las columnas del archivo ventas.csv, 
# excepto por la columna valor que solo está en ventas.csv

import pandas as pd

columnas_file_ventas = [
    'familia',
    'producto',
    'variacion',
    'salitre',
    'andino',
    'titan',
    'colina',
    'santafe',
    'fontanar',
    'chia',
    'calle 79',
    'calle 109',
    'calle 122',
    'cedritos',
    'fabrica',
    'valor'
]

columnas_file_stock = [
    'familia',
    'producto',
    'variacion',
    'salitre',
    'andino',
    'titan',
    'colina',
    'santafe',
    'fontanar',
    'chia',
    'calle 79',
    'calle 109',
    'calle 122',
    'cedritos',
]


sucursales = [
    "salitre",
    "andino",
    "titan",
    "colina",
    "santafe",
    "fontanar",
    "chia",
    "calle 79",
    "calle 109",
    "calle 122",
    "cedritos"
]


stock = pd.read_csv('test_stock.txt', sep='|')
ventas = pd.read_csv('ventas_mod/ventas.csv', sep='|')



ventas.columns = ventas.columns.str.lower()
stock.columns = stock.columns.str.lower()



if set(ventas.columns.tolist()) != set(columnas_file_ventas):
    raise ValueError("Las columnas del archivo de ventas no coinciden con las esperadas")

if set(stock.columns.tolist()) != set(columnas_file_stock):
    raise ValueError("Las columnas del archivo de stock no coinciden con las esperadas")



stock = stock.fillna('.')
ventas = ventas.fillna('.')
pd.set_option('display.width', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)



ventas['productos'] = ventas['producto'].str.strip()
ventas['variacion'] = ventas['variacion'].str.strip()
ventas['nombre'] = ventas['productos'].str.upper() + ' ' + ventas['variacion'].str.upper()
ventas['nombre'] = ventas['familia'].str.upper() + ' ' + ventas['producto'].str.upper() + ' ' + ventas['variacion'].str.upper()

stock['producto'] = stock['producto'].str.strip()
stock['variacion'] = stock['variacion'].str.strip()
stock['nombre'] = stock['familia'].str.upper() + ' ' + stock['producto'].str.upper() + ' ' + stock['variacion'].str.upper()


stock['nombre'] = stock['nombre'].astype(str).str.strip().str.replace(r'\s+', ' ', regex=True)
ventas['nombre'] = ventas['nombre'].astype(str).str.strip().str.replace(r'\s+', ' ', regex=True)


stock = stock.rename(
    columns={col: f"{col}_stock" for col in sucursales}
)
resultado = pd.merge(
    ventas,
    stock,
    on="nombre",
    how="outer",
    suffixes=("_ventas", "_stock")
)

#array de columnas para el resultado final
columnas = []
#columnas.append('familia_ventas')
columnas.append('nombre')
for sucursal in sucursales:
    
    columnas.append(f"{sucursal}")
    columnas.append(f"{sucursal}_stock")

columnas.append('fabrica')
columnas.append('valor')




for col in resultado.columns:
    if pd.api.types.is_numeric_dtype(resultado[col]):
        resultado[col] = pd.to_numeric(
            resultado[col], errors='coerce'
        ).round().astype('Int64')

mask = resultado['familia_ventas'].isna()

cols_numericas = resultado.select_dtypes(include='number').columns

resultado.loc[mask, cols_numericas] = (
    resultado.loc[mask, cols_numericas].fillna(0)
)


# poner valores vacios en las columnas stock
sucursales_stock = [f"{i}_stock" for i in sucursales]

resultado[sucursales_stock] = resultado[sucursales_stock].astype("Int64")


mask = ((resultado['familia_ventas'].isin([
   'BEBIDAS CALIENTES',
])) | (resultado['nombre'].isin([
    'MINI BITES POR 12 UNIDADES .',
    'MINI BITES POR 4 UNIDADES .',
    'MINI BITES POR 8 UNIDADES .'])))

resultado.loc[mask, sucursales_stock] = pd.NA
resultado['valor'] = pd.to_numeric(resultado['valor'], errors='coerce').round().astype('Int64')

resultado[columnas].to_csv('resultado.csv', sep='|', index=False)
#display(resultado[resultado['familia_ventas'] == 'BEBIDAS CALIENTES'][columnas])
#display(resultado[resultado['nombre'] == 'MINI BITES POR 12 UNIDADES .'][columnas])
display(resultado[columnas])
#display(ventas[ventas['producto'].str.contains('TARTALETA', na=False)])
#display(stock[stock['familia'].str.contains('BEBIDAS CALIENTES', na=False)])

,nombre,salitre,salitre_stock,andino,andino_stock,titan,titan_stock,colina,colina_stock,santafe,santafe_stock,fontanar,fontanar_stock,chia,chia_stock,calle 79,calle 79_stock,calle 109,calle 109_stock,calle 122,calle 122_stock,cedritos,cedritos_stock,fabrica,valor
0,ARITOS ARITO .,16,9,13,11,9,13,25,0,16,3,19,1,16,8,12,3,11,6,33,-7,29,4,33,5685300
1,ARITOS ARITO AREQUIPE .,2,1,6,0,5,0,3,0,3,0,2,0,2,1,2,1,0,2,2,2,3,1,0,721800
2,ARITOS ARITO CHOCOFLAN .,2,0,2,1,2,0,0,2,0,0,0,1,2,0,1,1,1,0,1,0,2,0,0,310700
3,ARITOS ARITO CHOCOLATE .,2,3,4,1,4,0,4,0,1,2,2,1,5,0,3,2,2,1,1,4,4,2,0,764800
4,ARITOS ARITO LIMON .,6,6,13,5,8,4,10,1,9,0,2,4,6,2,7,2,3,4,9,2,10,3,5,2136840
5,ARITOS ARITO MARACUYA .,7,4,7,1,8,0,8,1,7,0,5,0,6,0,2,2,3,3,7,1,10,0,2,1728120
6,ARITOS ARITO PISTACHO .,0,0,0,0,0,0,1,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,23900
7,BEBIDAS CALIENTES AMERICANO .,36,<NA>,48,<NA>,33,<NA>,61,<NA>,24,<NA>,33,<NA>,35,<NA>,13,<NA>,13,<NA>,36,<NA>,20,<NA>,0,2851200
8,BEBIDAS CALIENTES AMERICANO DOBLE .,0,<NA>,0,<NA>,1,<NA>,1,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,1,<NA>,0,<NA>,0,26100
9,BEBIDAS CALIENTES AROMATICA DE FRUTAS .,2,<NA>,3,<NA>,3,<NA>,2,<NA>,1,<NA>,5,<NA>,6,<NA>,1,<NA>,3,<NA>,4,<NA>,0,<NA>,0,273000
10,BEBIDAS CALIENTES AROMATICA HIERBABUENA .,6,<NA>,3,<NA>,6,<NA>,1,<NA>,2,<NA>,5,<NA>,1,<NA>,1,<NA>,0,<NA>,5,<NA>,0,<NA>,0,207000
11,BEBIDAS CALIENTES BLUE CHAI .,0,<NA>,1,<NA>,0,<NA>,0,<NA>,0,<NA>,3,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,2,<NA>,0,69000
12,BEBIDAS CALIENTES CAFÉ LATTE .,9,<NA>,15,<NA>,2,<NA>,8,<NA>,4,<NA>,10,<NA>,3,<NA>,0,<NA>,1,<NA>,8,<NA>,3,<NA>,0,711900
13,BEBIDAS CALIENTES CAPUCHINO .,2,<NA>,19,<NA>,33,<NA>,24,<NA>,12,<NA>,23,<NA>,19,<NA>,6,<NA>,11,<NA>,17,<NA>,12,<NA>,0,1958000
14,BEBIDAS CALIENTES CHAI AMATISTA .,0,<NA>,0,<NA>,2,<NA>,0,<NA>,1,<NA>,5,<NA>,2,<NA>,0,<NA>,0,<NA>,0,<NA>,2,<NA>,0,138000
15,BEBIDAS CALIENTES EXPRESSO .,2,<NA>,2,<NA>,0,<NA>,1,<NA>,0,<NA>,0,<NA>,2,<NA>,0,<NA>,0,<NA>,0,<NA>,1,<NA>,0,64800
16,BEBIDAS CALIENTES MACCHIATO .,2,<NA>,2,<NA>,0,<NA>,0,<NA>,1,<NA>,1,<NA>,1,<NA>,0,<NA>,1,<NA>,1,<NA>,0,<NA>,0,85500
17,BEBIDAS CALIENTES MILO .,1,<NA>,1,<NA>,2,<NA>,0,<NA>,0,<NA>,3,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,79100
18,BEBIDAS CALIENTES TE CHAI TE CHAI,0,<NA>,4,<NA>,2,<NA>,2,<NA>,0,<NA>,5,<NA>,2,<NA>,2,<NA>,0,<NA>,0,<NA>,2,<NA>,0,218500
19,BEBIDAS CALIENTES TE EN AGUA,0,<NA>,4,<NA>,2,<NA>,1,<NA>,1,<NA>,0,<NA>,1,<NA>,0,<NA>,0,<NA>,1,<NA>,2,<NA>,0,126000
20,BEBIDAS CALIENTES TE EN LECHE,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,1,<NA>,0,<NA>,0,<NA>,0,11900
21,BEBIDAS CALIENTES TE GOLDEN MILK .,0,4,0,6,0,5,0,3,0,5,0,0,0,14,0,4,0,5,0,0,0,0,0,0
22,BEBIDAS CALIENTES TE MATCHA .,3,<NA>,0,<NA>,1,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,1,<NA>,0,57500
23,BEBIDAS CALIENTES TE MATCHA CHAI .,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,1,<NA>,0,<NA>,0,<NA>,1,<NA>,0,<NA>,0,<NA>,0,23000
24,BOMBAS BOMBA GRANDE .,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,1,<NA>,1,<NA>,0,68000
25,BOMBAS BOMBA MEDIANA .,0,<NA>,1,<NA>,0,<NA>,1,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,38200
26,BROWNIES BROWNIE .,0,0,0,0,1,-1,1,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,23200
27,BROWNIES CAJA MINIBROWNIES X 16 .,0,1,1,2,0,1,3,-1,1,0,1,0,0,2,1,0,0,1,1,0,0,2,0,435900
28,BROWNIES CAJAMINI BROWNIES .,2,-2,2,-2,1,-1,1,-1,0,0,0,0,0,0,1,-1,0,0,1,-1,3,-3,1,345600
29,BROWNIES CHIPS NEGRO .,0,3,1,3,1,4,0,3,0,3,2,0,0,3,0,4,0,3,0,4,0,4,0,46400
30,BROWNIES CHOCOLATE .,2,3,6,1,3,2,3,3,3,2,5,0,3,2,1,4,3,3,3,4,3,2,0,407200
31,BROWNIES MINI BROWNIES .,0,0,0,0,0,0,0,0,1,10,0,0,2,0,1,2,24,-24,0,0,0,0,0,98500
32,BROWNIES M´M´S .,1,2,1,2,0,3,1,1,0,2,0,1,1,2,0,3,0,3,0,4,1,2,0,59200
33,BROWNIES OREO .,0,3,0,4,1,2,0,3,0,3,2,0,0,3,0,3,0,2,0,4,1,3,0,46400
34,CHEESECAKE BITE SIZE .,7,110,0,98,0,117,28,94,8,41,23,77,33,66,17,107,0,105,2,142,0,107,0,831600
35,CHEESECAKE CHEESECAKE SIN AZUCAR 1 NUMERO 6 PX,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,2,214200
36,CHEESECAKE CHEESECAKE SIN AZUCAR ARITO LIGHT,22,5,27,1,19,6,24,0,18,0,7,8,24,3,12,5,12,4,31,5,25,0,8,5687350
37,CHEESECAKE CHEESECAKE SIN AZUCAR DOBLE,2,1,0,2,1,1,1,2,1,0,1,1,1,0,1,1,1,1,0,3,2,1,1,2014800
38,CHEESECAKE CHEESECAKE SIN AZUCAR MEDIANO,4,4,0,6,4,4,4,4,3,3,3,3,3,6,2,8,4,4,11,2,10,4,4,6115000
39,CHEESECAKE CHEESECAKE SIN AZUCAR MEDIANO CORAZON,0,0,0,0,0,0,0,0,1,-1,1,-1,0,0,1,-1,2,-1,1,0,1,0,2,1079100
40,CHEESECAKE CHEESECAKE SIN AZUCAR MEDIANO CORAZON,0,2,0,2,0,1,0,2,1,1,1,1,0,1,1,2,2,1,1,1,1,2,2,1079100
41,CHEESECAKE CHEESECAKE SIN AZUCAR MINIMEDIANO,2,4,1,3,3,2,3,4,1,2,2,3,3,2,1,3,4,0,5,1,4,1,4,2638800
42,CHEESECAKE CHEESECAKE SIN AZUCAR MINIMEDIANO CORAZON,2,0,4,-1,0,2,2,1,1,1,1,1,1,1,0,2,2,0,2,1,3,0,0,1502100
43,CHEESECAKE CHEESECAKE SIN AZUCAR PX,5,1,14,4,8,4,12,0,0,0,25,0,8,0,5,13,0,0,5,13,12,0,0,1900400
44,CHEESECAKE CHEESECAKE SIN AZUCAR TRIPLE,0,1,0,1,1,2,0,1,0,0,0,1,1,0,0,0,0,1,2,1,1,1,1,1199800
45,CHEESECAKE CHEESECAKE TRADICIONAL DOBLE,3,0,0,2,0,2,1,1,1,2,1,-1,1,1,2,1,2,1,4,0,2,1,2,3098200
46,CHEESECAKE CHEESECAKE TRADICIONAL MEDIANO,0,9,1,7,4,1,3,4,0,6,4,4,0,8,2,7,2,7,8,5,10,1,2,4205600
47,CHEESECAKE CHEESECAKE TRADICIONAL MEDIANO CORAZON,1,1,1,1,1,1,2,0,1,0,0,2,1,0,0,2,2,0,4,-1,0,3,3,1918600
48,CHEESECAKE CHEESECAKE TRADICIONAL MINIMEDIANO,1,3,1,3,3,1,1,3,1,2,2,1,1,3,6,-1,1,3,4,2,3,2,3,2070000
49,CHEESECAKE CHEESECAKE TRADICIONAL MINIMEDIANO CORAZON,3,0,1,1,0,2,1,1,1,0,1,0,0,1,0,2,2,0,3,-1,1,0,2,1196000
50,CHEESECAKE CHEESECAKE TRADICIONAL PX,17,0,21,4,22,9,18,4,3,0,8,16,2,4,6,0,4,4,16,0,6,8,0,2471700
51,CHEESECAKE CHEESECAKE TRADICIONAL TRIPLE,0,1,1,0,2,0,1,0,0,1,1,0,1,0,0,1,0,2,2,0,2,0,2,2395800
52,CHEESECAKE ESPECIAL AMERICAN CUPS CHOCO OREO,1,1,2,0,0,0,1,1,1,1,0,0,1,1,1,2,2,1,2,1,1,2,0,264000
53,CHEESECAKE ESPECIAL AMERICAN CUPS CHOCORRAMO,1,1,1,3,3,0,2,1,2,0,0,2,1,0,0,2,0,2,0,3,0,0,0,220000
54,CHEESECAKE ESPECIAL AMERICAN CUPS FRAMBUESA,3,0,3,1,5,0,3,0,2,0,1,0,3,0,0,1,1,1,3,0,4,0,1,640200
55,CHEESECAKE ESPECIAL AMERICAN CUPS RED LEMON,1,0,0,1,1,0,1,0,0,0,2,0,1,0,0,2,2,0,2,0,0,0,0,222200
56,CHEESECAKE ESPECIAL AMERICAN CUPS SHORTCAKE,0,1,0,0,1,0,1,1,0,0,2,0,1,0,0,1,0,0,2,0,0,0,0,156200
57,CHEESECAKE ESPECIAL AMERICAN CUPS TRES LECHES ZERO,2,1,2,1,2,0,2,0,1,1,1,0,0,0,0,2,2,0,3,0,0,2,0,332200
58,CHEESECAKE ESPECIAL AMERICAN CUPS ZANAHORIA,2,1,1,1,2,0,2,0,2,0,1,1,1,1,2,1,1,1,2,0,1,2,0,367400
59,CHEESECAKE ESPECIAL ARITO ESPECIAL ARANDANOS,3,2,7,1,8,0,6,0,4,0,2,0,3,2,1,2,2,1,4,5,5,1,0,1153620
60,CHEESECAKE ESPECIAL ARITO ESPECIAL FRAMBUESA,5,0,10,1,8,0,5,0,4,0,2,0,3,0,2,3,4,0,6,1,4,2,0,1372860
61,CHEESECAKE ESPECIAL ARITO ESPECIAL VASCO,1,3,3,1,5,-1,2,0,0,0,0,0,1,2,2,0,1,1,1,2,2,1,0,451400
62,CHEESECAKE ESPECIAL ARITO ESPECIAL VASCO ARANDANO,2,2,3,2,2,0,1,1,3,0,1,0,3,-1,2,0,3,0,2,0,2,0,0,617200
63,CHEESECAKE ESPECIAL ARITO ESPECIAL VASCO LIMON,0,0,1,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,25500
64,CHEESECAKE ESPECIAL ARITO ESPECIAL VASCO ZERO,1,1,4,1,1,1,2,0,2,1,1,0,3,0,3,0,3,0,2,0,2,-1,0,604200
65,CHEESECAKE ESPECIAL DOBLE 15 PX FRUTOS ROJOS,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,2,376000
66,CHEESECAKE ESPECIAL MEDIANO 10 PX BLACKBERRY/BROWNIE,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,413900
67,CHEESECAKE ESPECIAL MEDIANO 10 PX BROWNIE,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,1,<NA>,0,133500
68,CHEESECAKE ESPECIAL MEDIANO 10 PX FRAMBUESA,1,1,1,1,2,0,1,0,0,1,0,1,1,1,1,0,2,0,1,0,1,0,1,1720900
69,CHEESECAKE ESPECIAL MEDIANO 10 PX FRUTOS ROJOS,2,3,1,2,3,-1,3,0,2,0,1,1,3,0,1,2,2,0,4,0,3,1,1,3538000
70,CHEESECAKE ESPECIAL MEDIANO 10 PX FRUTOS ROJOS ZERO,2,0,2,0,2,3,2,0,0,2,2,0,2,1,1,1,1,1,2,2,3,0,0,2630900
71,CHEESECAKE ESPECIAL MEDIANO 10 PX LIMON,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,413900
72,CHEESECAKE ESPECIAL MEDIANO 10 PX MARACUYA,1,0,1,0,1,0,1,0,1,0,0,1,1,0,1,0,0,1,1,1,0,1,1,1201500
73,CHEESECAKE ESPECIAL MEDIANO 10 PX NEW YOR,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
74,CHEESECAKE ESPECIAL MEDIANO 10 PX SOLO FRESAS CON MENSAJE,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,1,133500
75,CHEESECAKE ESPECIAL MONOPORCION ZERO FRUTOS ROJOS,2,5,10,1,7,7,7,1,6,6,8,0,6,0,1,5,5,5,12,0,5,6,0,1576700
76,CHEESECAKE ESPECIAL PORCION .,0,0,5,1,4,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,197100
77,CHEESECAKE MINI BITES POR 12 UNIDADES .,3,-3,4,-4,4,-4,3,-3,1,-1,3,-3,2,-2,3,-3,4,-4,3,-3,5,-5,9,3771600
78,CHEESECAKE MINI BITES POR 16 UNIDADES .,2,-2,2,-2,0,0,1,-1,1,-1,1,-1,1,-1,0,0,0,0,3,-3,0,0,0,1232000
79,CHEESECAKE MINI BITES POR 4 UNIDADES .,2,-2,0,0,1,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,84000
80,CHEESECAKE MINI BITES POR 8 UNIDADES .,3,-3,0,0,5,-5,1,-1,1,-1,0,0,1,-1,0,0,3,-3,7,-7,5,-5,2,1635200
81,CHOCOLATERIA COLOMBINAS .,0,<NA>,1,<NA>,2,<NA>,3,<NA>,0,<NA>,0,<NA>,0,<NA>,1,<NA>,0,<NA>,0,<NA>,0,<NA>,0,124300
82,CHOCOLATERIA VELAS PEQUEÑAS .,4,<NA>,3,<NA>,4,<NA>,1,<NA>,2,<NA>,1,<NA>,4,<NA>,3,<NA>,3,<NA>,6,<NA>,2,<NA>,1,605800
83,EMPAQUES EMPAQUE GRANDE .,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
84,EMPAQUES EMPAQUES PEQUEÑOS .,0,2,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0
85,EMPAQUES TARJETA REGALO .,0,0,0,0,0,0,0,20,0,10,0,0,0,0,0,11,0,0,0,0,0,0,0,0
86,GALLETERIA ALFAJORES .,2,2,2,5,2,3,3,4,0,5,3,1,8,-1,1,4,0,3,0,6,2,3,0,204700
87,GALLETERIA CAJA GALLETAS OJITOS MERMELADA .,1,0,0,1,0,1,0,1,1,0,1,0,0,1,1,1,1,0,1,0,1,0,0,275200
88,GALLETERIA CAJA GALLETAS SURTIDAS .,0,1,0,2,0,1,0,1,1,0,0,1,1,0,1,0,1,0,1,0,0,1,0,191000
89,GALLETERIA CORAZONES ACHOCOLATADOS .,2,3,7,2,3,3,6,1,0,5,7,0,9,0,2,4,0,5,8,1,1,10,0,315000
90,GALLETERIA GALLETAS AVENA .,0,5,0,4,1,4,2,2,0,2,1,4,0,6,1,3,0,2,0,5,1,1,0,61800
91,GALLETERIA GALLETAS CHOCOLACHIPS .,0,3,2,0,2,2,1,3,0,2,2,1,0,3,0,3,0,3,1,1,2,2,0,103000
92,GALLETERIA GALLETAS OJITOS MERMELADA .,3,4,3,3,2,8,2,5,4,1,11,0,4,7,8,4,5,1,9,0,3,11,0,237600
93,GALLETERIA GALLETERIA ALMENDRA,3,3,0,4,0,3,7,-2,2,2,3,0,2,4,0,2,0,3,0,0,0,2,0,61200
94,GALLETERIA MINI ALFAJORES .,4,6,15,2,4,3,11,1,4,3,7,5,8,2,4,5,7,4,4,4,2,8,0,252000
95,GALLETERIA PAQUETICO GALLETA JALEA .,0,0,0,0,0,3,1,2,0,1,0,0,4,0,0,7,0,4,3,12,6,1,0,64400
96,GRUPO BEBIDAS FRIAS AGUA CON GAS .,0,16,12,6,3,12,10,5,5,4,10,8,3,11,0,15,1,8,11,6,0,15,0,418000
97,GRUPO BEBIDAS FRIAS AGUA NORMAL .,4,32,48,51,8,36,31,-1,5,24,23,9,22,2,3,19,3,19,5,17,6,25,0,1200800
98,GRUPO BEBIDAS FRIAS BRETAÑA .,0,<NA>,4,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,2,<NA>,0,52200
99,GRUPO BEBIDAS FRIAS GASEOSA COCACOLA DIETY,2,17,7,15,5,7,4,5,1,5,8,1,2,5,1,11,2,3,5,4,2,7,0,342000
100,GRUPO BEBIDAS FRIAS GASEOSA COCACOLA NORMAL,2,15,9,11,0,14,0,0,0,10,1,7,3,1,0,11,1,9,3,4,3,10,0,192300
101,GRUPO BEBIDAS FRIAS HATSU .,0,9,5,10,3,8,4,0,0,1,0,6,3,3,1,8,2,4,0,9,1,7,0,178600
102,GRUPO BEBIDAS FRIAS JUGO AGUA,1,-1,0,0,4,-4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,53500
103,GRUPO BEBIDAS FRIAS JUGO LECHE,0,0,1,-1,1,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22400
104,GRUPO BEBIDAS FRIAS LIMONADA FRAMBUESA,0,6,1,1,0,1,2,0,0,0,3,1,1,1,1,3,1,3,0,7,0,5,0,103500
105,GRUPO BEBIDAS FRIAS LIMONADA SANDIA Y ALBAHACA,0,6,1,4,2,3,1,0,1,0,0,4,1,2,0,5,1,3,0,5,2,3,0,103500
106,GRUPO BEBIDAS FRIAS MILO FRIO .,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,0,0,0,1,-1,0,0,0,11300
107,GRUPO BEBIDAS FRIAS MR. TE .,2,10,0,14,1,11,6,2,2,3,2,8,0,0,0,6,0,8,0,11,0,11,0,75400
108,GRUPO BEBIDAS FRIAS SODA DE FRUTA FREIJOA,0,0,0,5,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,6,0,3,0,0
109,GRUPO BEBIDAS FRIAS SODA DE FRUTA FRUTOS ROJOS,0,4,0,4,0,0,0,0,0,0,1,3,0,0,0,4,0,0,0,0,0,3,0,13000
110,GRUPO BEBIDAS FRIAS SODA DE FRUTA FRUTOS VERDES,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
111,GRUPO BEBIDAS FRIAS SODA DE FRUTA LULO,0,3,1,2,0,0,0,0,0,0,1,2,0,0,0,3,0,0,1,3,0,4,0,39000
112,GRUPO BEBIDAS FRIAS SODA DE FRUTA MARACUYA,0,1,1,3,0,0,0,0,0,0,1,3,0,0,0,1,0,0,0,5,0,2,0,26000
113,GRUPO BEBIDAS FRIAS VASO LECHE .,1,-1,0,0,1,-1,0,0,0,0,0,0,0,0,0,0,1,-1,0,0,0,0,0,20700
114,HOJALDRES DE SAL PALOS DE QUESO .,4,0,6,3,5,1,6,2,1,2,10,0,4,6,0,4,2,1,1,5,1,4,0,436000
115,HOJALDRES DE SAL PASTELES DE POLLO .,2,3,3,5,6,1,7,0,2,1,20,1,11,0,0,5,5,0,5,0,2,5,0,774900
116,MILHOJAS PXVAINILLA AREQUIPE .,3,3,15,0,5,0,10,0,4,1,0,0,4,0,4,0,0,0,5,0,0,4,1,816000
117,PIE LIMON MINI .,3,4,7,2,5,0,8,0,4,1,5,0,2,5,5,0,6,2,5,3,4,1,2,1310600
118,PIE PIE MANZANA .,1,1,4,0,4,0,0,3,2,1,1,1,0,3,3,0,0,0,3,1,2,2,0,458600
119,PONQUES MINIPONQUE FRUTOS ROJOS,1,1,1,1,2,0,1,1,0,1,0,0,1,1,2,0,0,0,1,1,1,1,0,299600
120,PONQUES MINIPONQUE KINDER,1,0,1,0,1,0,0,0,0,0,1,0,1,0,1,0,1,0,0,0,0,1,0,232500
121,PONQUES MINIPONQUE M´M´S,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,1,31000
122,PONQUES MINIPONQUE NUTELLA,1,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,31000
123,PONQUES MINIPONQUE OREO,1,2,2,0,2,1,3,0,3,0,1,0,1,1,1,0,2,1,1,1,0,1,0,536300
124,PONQUES MINIPONQUE REDVELVET,3,1,1,3,3,0,4,0,2,0,2,1,1,2,2,0,0,2,3,0,2,1,6,887400
125,PONQUES MINIPONQUE REDVELVET ESPECIAL,2,0,2,1,1,2,3,0,2,0,2,0,3,0,2,1,1,2,3,0,3,0,0,722500
126,PONQUES MINIPONQUE T. CHOCOLATE SIN AZUCAR AÑADIDO,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,127100
127,PONQUES PX .,0,<NA>,5,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,80500
128,PONQUES TORTA 12 PX KINDER,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,1,137500
129,PONQUES TORTA 12 PX NUTELLA,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,1,137500
130,PONQUES TORTA 12 PX OREO,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,148500
131,PONQUES TORTA 12 PX REDVELVET,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
132,PONQUES TORTA 12 PX SELVA NEGRA,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,2,297000
133,PONQUES TORTA 8 PX CHOCOFRAMBUESA,0,<NA>,0,<NA>,1,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,1,<NA>,0,<NA>,0,<NA>,0,<NA>,0,204800
134,PONQUES TORTA 8 PX GANACHE,0,0,1,0,1,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,367800
135,PONQUES TORTA 8 PX KINDER,0,1,0,1,1,0,1,0,0,1,0,1,1,1,1,0,1,1,1,0,0,1,0,589300
136,PONQUES TORTA 8 PX NUTELLA,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
137,PONQUES TORTA 8 PX RED VELVET,1,0,0,1,1,0,1,0,1,0,1,1,0,1,1,0,1,0,0,1,0,1,1,726600
138,PONQUES TORTA 8 PX SELVA NEGRA,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,102400
139,PONQUES TORTA 8 PX SHORTCAKE,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,89700
140,PONQUES TORTA 8 PX T. CHOCOL,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,-1,0,0,0,0,0,102400
141,PONQUES TORTA 8 PX ZANAHORIA,0,1,1,0,1,0,0,1,0,1,1,0,0,1,0,1,1,0,2,0,1,0,0,627900
142,PROMOCIONES CHEESECAKE & CAFFEE .,0,0,0,0,0,0,0,0,0,0,0,0,3,-3,0,0,0,0,0,0,0,0,0,71700
143,PROMOCIONES PROMOCION 3X4 CHEESE CAKE TRADICIONAL .,0,0,1,-1,1,-1,0,0,0,0,0,0,1,-1,0,0,1,-1,0,0,1,-1,0,366850
144,PROMOCIONES PROMOCION 3X4 CHEESE LIGHT .,0,0,0,0,1,-1,0,0,0,0,0,0,0,0,2,-2,0,0,2,-2,1,-1,1,488400
145,TARTALETA TARTALETA NORMAL GRANDE 12 PX,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,175600
146,TARTALETA TARTALETA NORMAL GRANDE 20 PX,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,1,211200
147,TARTALETA TARTALETA NORMAL MEDIANA 8 PX,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,3,-1,3,1,0,1001200
148,TARTALETA TARTALETA NORMAL MINITARTALETA,10,1,14,1,14,-2,14,0,2,8,9,0,3,9,5,2,7,5,10,4,16,-3,4,2828080
149,TARTALETA TARTALETA NORMAL PX,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,20100
150,TARTALETA TARTALETA SIN AZUCAR GRANDE 12 PX,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
151,TARTALETA TARTALETA SIN AZUCAR MEDIANA 8 PX,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,433200
152,TARTALETA TARTALETA SIN AZUCAR MINITARTALETA,9,5,11,2,8,2,12,1,5,5,9,0,12,-1,2,4,5,3,11,2,14,-2,2,2638310
153,TARTALETA TARTALETA SIN AZUCAR PX,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,2,<NA>,0,<NA>,0,42400
154,TOPPERS TOPPERS GRANDE .,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,1,<NA>,1,28000
155,TORTA 3 LECHES COPITAS T. 3 LECHES .,2,1,1,2,3,0,2,1,1,0,0,0,2,0,2,0,1,1,0,3,0,3,0,316300
156,TORTA 3 LECHES T. 3 LECHES TORTA 8 PX .,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,179400
157,VARIOS DOMICILIO .,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,0,<NA>,38,475000